# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from chopflow._generated import chopflow_pb2 as chopflow__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chopflow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChopFlowBrokerStub:
    """The ChopFlow broker service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnqueueTask = channel.unary_unary(
                '/chopflow.ChopFlowBroker/EnqueueTask',
                request_serializer=chopflow__pb2.EnqueueTaskRequest.SerializeToString,
                response_deserializer=chopflow__pb2.EnqueueTaskResponse.FromString,
                _registered_method=True)
        self.GetTaskStatus = channel.unary_unary(
                '/chopflow.ChopFlowBroker/GetTaskStatus',
                request_serializer=chopflow__pb2.GetTaskStatusRequest.SerializeToString,
                response_deserializer=chopflow__pb2.GetTaskStatusResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/chopflow.ChopFlowBroker/CancelTask',
                request_serializer=chopflow__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=chopflow__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.RegisterWorker = channel.unary_unary(
                '/chopflow.ChopFlowBroker/RegisterWorker',
                request_serializer=chopflow__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=chopflow__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.WorkerHeartbeat = channel.unary_unary(
                '/chopflow.ChopFlowBroker/WorkerHeartbeat',
                request_serializer=chopflow__pb2.WorkerHeartbeatRequest.SerializeToString,
                response_deserializer=chopflow__pb2.WorkerHeartbeatResponse.FromString,
                _registered_method=True)
        self.AcknowledgeTask = channel.unary_unary(
                '/chopflow.ChopFlowBroker/AcknowledgeTask',
                request_serializer=chopflow__pb2.AcknowledgeTaskRequest.SerializeToString,
                response_deserializer=chopflow__pb2.AcknowledgeTaskResponse.FromString,
                _registered_method=True)
        self.FetchTasks = channel.unary_unary(
                '/chopflow.ChopFlowBroker/FetchTasks',
                request_serializer=chopflow__pb2.FetchTasksRequest.SerializeToString,
                response_deserializer=chopflow__pb2.FetchTasksResponse.FromString,
                _registered_method=True)
        self.GetQueueStats = channel.unary_unary(
                '/chopflow.ChopFlowBroker/GetQueueStats',
                request_serializer=chopflow__pb2.GetQueueStatsRequest.SerializeToString,
                response_deserializer=chopflow__pb2.GetQueueStatsResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/chopflow.ChopFlowBroker/ListTasks',
                request_serializer=chopflow__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=chopflow__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.ListWorkers = channel.unary_unary(
                '/chopflow.ChopFlowBroker/ListWorkers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=chopflow__pb2.ListWorkersResponse.FromString,
                _registered_method=True)
        self.CreateSchedule = channel.unary_unary(
                '/chopflow.ChopFlowBroker/CreateSchedule',
                request_serializer=chopflow__pb2.CreateScheduleRequest.SerializeToString,
                response_deserializer=chopflow__pb2.CreateScheduleResponse.FromString,
                _registered_method=True)
        self.ListSchedules = channel.unary_unary(
                '/chopflow.ChopFlowBroker/ListSchedules',
                request_serializer=chopflow__pb2.ListSchedulesRequest.SerializeToString,
                response_deserializer=chopflow__pb2.ListSchedulesResponse.FromString,
                _registered_method=True)
        self.DeleteSchedule = channel.unary_unary(
                '/chopflow.ChopFlowBroker/DeleteSchedule',
                request_serializer=chopflow__pb2.DeleteScheduleRequest.SerializeToString,
                response_deserializer=chopflow__pb2.DeleteScheduleResponse.FromString,
                _registered_method=True)


class ChopFlowBrokerServicer:
    """The ChopFlow broker service
    """

    def EnqueueTask(self, request, context):
        """Task management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """Worker management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WorkerHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgeTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchTasks(self, request, context):
        """Task delivery: workers pull tasks they are capable of executing.
        The broker matches queued tasks against the worker's tags and
        available resources and returns up to `max_tasks` ready tasks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueueStats(self, request, context):
        """Queue stats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSchedule(self, request, context):
        """Schedule management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChopFlowBrokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnqueueTask': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueTask,
                    request_deserializer=chopflow__pb2.EnqueueTaskRequest.FromString,
                    response_serializer=chopflow__pb2.EnqueueTaskResponse.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=chopflow__pb2.GetTaskStatusRequest.FromString,
                    response_serializer=chopflow__pb2.GetTaskStatusResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=chopflow__pb2.CancelTaskRequest.FromString,
                    response_serializer=chopflow__pb2.CancelTaskResponse.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=chopflow__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=chopflow__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'WorkerHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.WorkerHeartbeat,
                    request_deserializer=chopflow__pb2.WorkerHeartbeatRequest.FromString,
                    response_serializer=chopflow__pb2.WorkerHeartbeatResponse.SerializeToString,
            ),
            'AcknowledgeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeTask,
                    request_deserializer=chopflow__pb2.AcknowledgeTaskRequest.FromString,
                    response_serializer=chopflow__pb2.AcknowledgeTaskResponse.SerializeToString,
            ),
            'FetchTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchTasks,
                    request_deserializer=chopflow__pb2.FetchTasksRequest.FromString,
                    response_serializer=chopflow__pb2.FetchTasksResponse.SerializeToString,
            ),
            'GetQueueStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueStats,
                    request_deserializer=chopflow__pb2.GetQueueStatsRequest.FromString,
                    response_serializer=chopflow__pb2.GetQueueStatsResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=chopflow__pb2.ListTasksRequest.FromString,
                    response_serializer=chopflow__pb2.ListTasksResponse.SerializeToString,
            ),
            'ListWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=chopflow__pb2.ListWorkersResponse.SerializeToString,
            ),
            'CreateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchedule,
                    request_deserializer=chopflow__pb2.CreateScheduleRequest.FromString,
                    response_serializer=chopflow__pb2.CreateScheduleResponse.SerializeToString,
            ),
            'ListSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchedules,
                    request_deserializer=chopflow__pb2.ListSchedulesRequest.FromString,
                    response_serializer=chopflow__pb2.ListSchedulesResponse.SerializeToString,
            ),
            'DeleteSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchedule,
                    request_deserializer=chopflow__pb2.DeleteScheduleRequest.FromString,
                    response_serializer=chopflow__pb2.DeleteScheduleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chopflow.ChopFlowBroker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chopflow.ChopFlowBroker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChopFlowBroker:
    """The ChopFlow broker service
    """

    @staticmethod
    def EnqueueTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chopflow.ChopFlowBroker/EnqueueTask',
            chopflow__pb2.EnqueueTaskRequest.SerializeToString,
            chopflow__pb2.EnqueueTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chopflow.ChopFlowBroker/GetTaskStatus',
            chopflow__pb2.GetTaskStatusRequest.SerializeToString,
            chopflow__pb2.GetTaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chopflow.ChopFlowBroker/CancelTask',
            chopflow__pb2.CancelTaskRequest.SerializeToString,
            chopflow__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chopflow.ChopFlowBroker/RegisterWorker',
            chopflow__pb2.RegisterWorkerRequest.SerializeToString,
            chopflow__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WorkerHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chopflow.ChopFlowBroker/WorkerHeartbeat',
            chopflow__pb2.WorkerHeartbeatRequest.SerializeToString,
            chopflow__pb2.WorkerHeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcknowledgeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chopflow.ChopFlowBroker/AcknowledgeTask',
            chopflow__pb2.AcknowledgeTaskRequest.SerializeToString,
            chopflow__pb2.AcknowledgeTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chopflow.ChopFlowBroker/FetchTasks',
            chopflow__pb2.FetchTasksRequest.SerializeToString,
            chopflow__pb2.FetchTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueueStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chopflow.ChopFlowBroker/GetQueueStats',
            chopflow__pb2.GetQueueStatsRequest.SerializeToString,
            chopflow__pb2.GetQueueStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chopflow.ChopFlowBroker/ListTasks',
            chopflow__pb2.ListTasksRequest.SerializeToString,
            chopflow__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chopflow.ChopFlowBroker/ListWorkers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            chopflow__pb2.ListWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chopflow.ChopFlowBroker/CreateSchedule',
            chopflow__pb2.CreateScheduleRequest.SerializeToString,
            chopflow__pb2.CreateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chopflow.ChopFlowBroker/ListSchedules',
            chopflow__pb2.ListSchedulesRequest.SerializeToString,
            chopflow__pb2.ListSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chopflow.ChopFlowBroker/DeleteSchedule',
            chopflow__pb2.DeleteScheduleRequest.SerializeToString,
            chopflow__pb2.DeleteScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
