[package]
name = "chopflow_worker"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Worker for ChopFlow distributed task queue"
repository.workspace = true
license.workspace = true

[dependencies]
chopflow_core = { path = "../core", version = "0.1.3" }
chopflow-proto = { path = "../proto", version = "0.1.3" }
tokio.workspace = true
clap.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
config.workspace = true
tonic.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
futures.workspace = true

[dev-dependencies]
chopflow_broker = { path = "../broker", version = "0.1.3" }
tokio = { workspace = true, features = ["full", "test-util"] }
tempfile = "3"
